---
Name: toastcolours
---

Page:
  extensions:
    - Toast\ThemeColours\Extensions\PageExtension
PageController:
  extensions:
    - Toast\ThemeColours\Extensions\PageControllerExtension

Toast\ThemeColours\Models:
  default_colours:
    - primary: null
    - secondary: null
    - black: '000000'
    - white: 'ffffff'
  css_folder_path: '/public/assets/styles/'

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Toast\ThemeColours\Extensions\SiteConfigExtension

SilverStripe\ORM\DatabaseAdmin:
  extensions:
    - Toast\ThemeColours\Extensions\DatabaseAdminExtension
